export type Product = {
  id: string
  name: string
  price: number
  rating: number
  sold: number
  location: string
  imageAlt?: string
  imageQuery?: string
}

export const products: Product[] = [
  {
    id: "p-001",
    name: "Headphone Wireless Bass Boost 40mm Driver",
    price: 349000,
    rating: 4.7,
    sold: 2300,
    location: "Jakarta Pusat",
    imageAlt: "Headphone wireless hitam",
    imageQuery: "headphone wireless black studio product photography",
  },
  {
    id: "p-002",
    name: "Keyboard Mekanik 87 Keys RGB Hot-Swap",
    price: 599000,
    rating: 4.8,
    sold: 5400,
    location: "Bandung",
    imageAlt: "Keyboard mekanik RGB",
    imageQuery: "mechanical keyboard rgb white keycaps",
  },
  {
    id: "p-003",
    name: "Mouse Wireless Ergonomis Silent Click",
    price: 129000,
    rating: 4.6,
    sold: 1200,
    location: "Surabaya",
    imageAlt: "Mouse wireless ergonomis",
    imageQuery: "ergonomic wireless mouse minimal product",
  },
  {
    id: "p-004",
    name: 'Monitor 27" IPS 2K 165Hz Bezel Tipis',
    price: 3399000,
    rating: 4.9,
    sold: 980,
    location: "Jakarta Barat",
    imageAlt: "Monitor 27 inci IPS",
    imageQuery: "27 inch ips monitor high resolution display",
  },
  {
    id: "p-005",
    name: "Webcam Full HD 1080p Autofocus",
    price: 259000,
    rating: 4.5,
    sold: 2200,
    location: "Yogyakarta",
    imageAlt: "Webcam Full HD",
    imageQuery: "webcam 1080p autofocus black",
  },
  {
    id: "p-006",
    name: "Mic Condenser USB untuk Streaming",
    price: 399000,
    rating: 4.7,
    sold: 1750,
    location: "Bekasi",
    imageAlt: "Microphone condenser USB",
    imageQuery: "usb condenser microphone streaming setup",
  },
  {
    id: "p-007",
    name: "Kursi Gaming Adjustable Lumbar Support",
    price: 1499000,
    rating: 4.6,
    sold: 870,
    location: "Semarang",
    imageAlt: "Kursi gaming hitam",
    imageQuery: "gaming chair black ergonomic",
  },
  {
    id: "p-008",
    name: "Meja Kerja Minimalis Kayu Solid 120cm",
    price: 899000,
    rating: 4.7,
    sold: 1160,
    location: "Denpasar",
    imageAlt: "Meja kerja minimalis",
    imageQuery: "minimalist wooden desk home office",
  },
  {
    id: "p-009",
    name: "Lampu Meja LED Dimmable 5 Mode",
    price: 179000,
    rating: 4.5,
    sold: 2100,
    location: "Depok",
    imageAlt: "Lampu meja LED",
    imageQuery: "led desk lamp dimmable modern",
  },
  {
    id: "p-010",
    name: "SSD NVMe 1TB Gen4 7000MB/s",
    price: 1299000,
    rating: 4.9,
    sold: 3200,
    location: "Jakarta Timur",
    imageAlt: "SSD NVMe 1TB",
    imageQuery: "nvme ssd m2 1tb product",
  },
  {
    id: "p-011",
    name: 'Tas Ransel Anti Air 20L Laptop 15"',
    price: 279000,
    rating: 4.6,
    sold: 2650,
    location: "Bandung",
    imageAlt: "Tas ransel anti air",
    imageQuery: "waterproof backpack laptop 15 inch",
  },
  {
    id: "p-012",
    name: "Sepatu Lari Ringan Breathable",
    price: 349000,
    rating: 4.7,
    sold: 1980,
    location: "Surabaya",
    imageAlt: "Sepatu lari breathable",
    imageQuery: "running shoes breathable mesh",
  },
  {
    id: "p-013",
    name: 'Smartwatch AMOLED 1.75" GPS',
    price: 899000,
    rating: 4.6,
    sold: 1400,
    location: "Jakarta Selatan",
    imageAlt: "Smartwatch AMOLED",
    imageQuery: "smartwatch amoled black sport",
  },
  {
    id: "p-014",
    name: "Kamera Mirrorless 24MP Kit Lens",
    price: 6799000,
    rating: 4.8,
    sold: 680,
    location: "Makassar",
    imageAlt: "Kamera mirrorless 24MP",
    imageQuery: "mirrorless camera 24mp kit lens",
  },
  {
    id: "p-015",
    name: "Lensa 50mm f/1.8 Prime",
    price: 1999000,
    rating: 4.7,
    sold: 740,
    location: "Tangerang",
    imageAlt: "Lensa 50mm f1.8",
    imageQuery: "50mm f1.8 camera lens product",
  },
  {
    id: "p-016",
    name: "Power Bank 20.000mAh PD 30W",
    price: 299000,
    rating: 4.6,
    sold: 4100,
    location: "Bogor",
    imageAlt: "Power bank hitam",
    imageQuery: "power bank 20000mah pd charging",
  },
  {
    id: "p-017",
    name: "Earbuds TWS ANC Bluetooth 5.3",
    price: 459000,
    rating: 4.7,
    sold: 2900,
    location: "Malang",
    imageAlt: "Earbuds TWS ANC",
    imageQuery: "tws earbuds anc white product",
  },
  {
    id: "p-018",
    name: 'Tablet 11" 2K 8GB/256GB',
    price: 3699000,
    rating: 4.5,
    sold: 830,
    location: "Pontianak",
    imageAlt: "Tablet layar 11 inci",
    imageQuery: "11 inch tablet 2k display productivity",
  },
  {
    id: "p-019",
    name: "Router WiFi 6 AX3000",
    price: 749000,
    rating: 4.6,
    sold: 1650,
    location: "Palembang",
    imageAlt: "Router WiFi 6",
    imageQuery: "wifi 6 router ax3000 product",
  },
  {
    id: "p-020",
    name: "Humidifier Ultrasonic 3L Auto-Off",
    price: 199000,
    rating: 4.5,
    sold: 2100,
    location: "Medan",
    imageAlt: "Humidifier 3 liter",
    imageQuery: "ultrasonic humidifier white minimalist",
  },
  {
    id: "p-021",
    name: "Action Cam 4K Stabilization",
    price: 1599000,
    rating: 4.6,
    sold: 920,
    location: "Padang",
    imageAlt: "Action camera 4K",
    imageQuery: "action camera 4k waterproof",
  },
  {
    id: "p-022",
    name: "Blender Portable 500ml USB-C",
    price: 149000,
    rating: 4.4,
    sold: 3100,
    location: "Solo",
    imageAlt: "Blender portable",
    imageQuery: "portable blender 500ml usb c",
  },
  {
    id: "p-023",
    name: "Rice Cooker Mini 1L",
    price: 229000,
    rating: 4.5,
    sold: 1800,
    location: "Cirebon",
    imageAlt: "Rice cooker mini",
    imageQuery: "mini rice cooker 1l white",
  },
  {
    id: "p-024",
    name: "Set Panci Stainless 5-in-1",
    price: 399000,
    rating: 4.6,
    sold: 1250,
    location: "Manado",
    imageAlt: "Set panci stainless",
    imageQuery: "stainless steel pot set kitchen",
  },
]
